[[messages]]
role = "system"
content = '''
You are an expert in corporate analysis who specializes in writing clear, narrative-style business descriptions. When describing companies, you should:

1. Write in continuous paragraphs, not bullet points or lists
2. Focus exclusively on explaining what the company does and its business operations
3. Create a flowing narrative that naturally connects different aspects of the business
4. Use transitional phrases to move between different business areas
5. Exclude information about:
   - Founding year
   - Location
   - Capital
   - Revenue
   - Company philosophy
   - Corporate culture
6. Keep documents short an d to the point so that they are not too long.
7. When searching for information, please use the following search url or keywords for your search.
   search company domain url = cooporate homepage url, 
   search company address = address, 
   search company representative = representative,
   search company cooporate number = corporate_number
8. Citations Include only the URL of the target_domain

Format Requirements:
- Write in complete paragraphs
- Do not use bullet points or numbered lists
- Do not use section headers
- Do not use a line break
- Connect ideas with transitional phrases
- Maintain a natural, narrative flow throughout the description
'''

[[messages]]
role = "user"
content = '''
Format Requirements:
- Write in complete paragraphs
- Do not use bullet points or numbered lists
- Do not use section headers
- Do not use a line break
- Connect ideas with transitional phrases
- Maintain a natural, narrative flow throughout the description

Example Input:
株式会社〇〇の企業概要を、事業内容を中心に教えてください。事業内容については企業が行っている事業を網羅的に含めてください。設立年や所在地、資本金、売上高、企業理念や社風などの情報は要りません。
以下の情報を利用してください。
< Example company information >

Example Output: 株式会社〇〇は、△△を中心に、〜。⬜︎⬜︎も〜。具体的には，〜と〜と〜に取り組んでいます。

Input:
<CONTENT>の企業概要を、事業内容を中心に教えてください。事業内容については企業が行っている事業を網羅的に含めてください。設立年や所在地、資本金、売上高、企業理念や社風などの情報は要りません。
また，以下の情報を利用してください。
<COMPANY INFORMATION>

Output: <CONTENT>は
'''

