name: Docker Build and Push

on:
  push:
    paths:
      - 'docker/**'    # docker/ディレクトリ以下の変更を監視
    branches:
      - main

env:
  BASE_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/llm_search

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Free disk space
        run: |
          docker system prune -af
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*
          df -h

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
    
      - name: Get version from .env.version
        id: version
        run: VERSION=$(cat docker/.env.version) && echo "version=$VERSION" >> $GITHUB_OUTPUT


      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: docker    # コンテキストをdockerディレクトリに変更
          file: docker/Dockerfile
          push: true
          tags: |
            ${{ env.BASE_IMAGE_NAME }}:latest
            ${{ env.BASE_IMAGE_NAME }}:${{ steps.version.outputs.version }}
          cache-from: type=registry,ref=${{ env.BASE_IMAGE_NAME }}:latest
          cache-to: type=inline